grid_map_filters:

  # Compute surface normals.
  - name: surface_normals
    type: gridMapFilters/NormalVectorsFilter
    params:
      input_layer: elevation
      output_layers_prefix: normal_vectors_
      radius: 0.6 # 0.25
      normal_vector_positive_axis: z
  
  - name: slope_dilating_5
    type: gridMapFilters/SlidingWindowMathExpressionFilter
    params:
      input_layer: normal_vectors_z
      output_layer: dilated_slope_5
      expression: 'max(acos(normal_vectors_z))'
      compute_empty_cells: false
      edge_handling: mean # options: inside, crop, empty, mean
      window_size: 5

  # Inflating the slope.
  # - name: edge_detection
  #   type: gridMapFilters/MeanInRadiusFilter
  #   params:
  #     input_layer: slope
  #     output_layer: inflated_slope
  #     radius: 0.6 