global_frame: t265_odom_frame
robot_base_frame: base_link
update_frequency: 10.0
publish_frequency: 10.0
rolling_window: false
# always_send_full_costmap: false
# obstacle_range:           6
# raytrace_range:           3.0
transform_tolerance: 2
footprint:
  [[-0.153, -0.1405], [-0.153, 0.1405], [0.153, 0.1405], [0.153, -0.1405]]

plugins:
  - { name: static, type: "costmap_2d::StaticLayer" }
  - { name: inflation, type: "costmap_2d::InflationLayer" }
  # - {name: obstacles, type: "costmap_2d::obstacles"}

inflation:
  inflation_radius: 0.55

static:
  map_topic: /maro_map
  lethal_cost_threshold: 100
  subscribe_to_updates: true
