global_frame:              /map
robot_base_frame:          base_link
update_frequency:          20.0
static_map:                true

# publish_frequency:       5.0
# rolling_window:          false

# obstacle_range:          2.5
# raytrace_range:          3.0
footprint:                 [[-0.153, -0.1405], [-0.153, 0.1405], [0.153, 0.1405], [0.153, -0.1405]]
#robot_radius:             ir_of_robot
inflation_radius:          0.55

plugins:
    - {name: static, type: "costmap_2d::StaticLayer"}

static:
    map_topic:             /maro_map
    lethal_cost_threshold: 100
