local_costmap:
  global_frame: base_footprint
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  transform_tolerance: 100000

  obstacle_range: 2.5
  raytrace_range: 3.0

  plugins: 
    - {name: obstacles, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  
  obstacles:
    enabled: true
    origin_z: 0.0
    z_resolution: 0.05
    z_voxels: 15
    mark_threshold: 3
    publish_voxel_map: true    
    max_obstacle_height: 3.0
    observation_sources: rgbd_camera

    rgbd_camera:
      data_type: PointCloud2
      topic: /zed2/point_cloud/cloud_registered
      marking: true
      # clearing: true
      obstacle_range: 3.0
      raytrace_range: 3.0
      max_obstacle_height: 3.0
      min_obstacle_height: -1.5

  inflation_layer:
    inflation_radius: 0.15
