global_frame: t265_odom_frame
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 5.0
rolling_window: true
width: 5
height: 5
transform_tolerance: 2
footprint: [[-0.45, -0.375], [0.45, -0.375], [0.45, 0.375], [-0.45, 0.375]]
